### ISSUE TITLE
Use UpdateFieldsForEntity instead of UpdateEntity

### ISSUE THREAD

**Issue by maansson** [stefanolsen/inriver-extensions#1]
If you have another EntityListener with the same logic (load entity, to changes, update entity) they will compete for the revision of the Entity. 

If you use UpdateFieldsForEntity() the server handles the revisions instead. That method is also faster.

**Comment by stefanolsen** [comment]
Good catch. I have replaced those method calls in 253d4c3e7a6798407d2a2b61b41b53828fd67416.
